jobs:
  validate:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: trussworks/circleci:29ab89fdada1f85c5d8fb685a2c71660f0c5f60c
    steps:
    - checkout
    - restore_cache:
        keys:
        - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
    - run:
        command: pre-commit run --all-files
        name: Run pre-commit tests
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
        - ~/.cache/pre-commit
references:
  circleci: trussworks/circleci:29ab89fdada1f85c5d8fb685a2c71660f0c5f60c
version: 2.1
workflows:
  validate:
    jobs:
    - validate:
        context:
        - org-global
  version: 2.1
